# db/migrations/env.py
"""Alembic's entrypoint. No ORM models exist yet -- this is the schema-
*versioning* half of the SQLAlchemy ORM + Alembic migration only; ORM model
adoption is a later, separate phase -- so target_metadata is None: every
migration in versions/ is hand-written (op.execute(raw SQL)), not
autogenerated by diffing against declarative model classes.

sqlalchemy.url is deliberately NOT set in alembic.ini -- resolved here, at
run time, via db.connection.get_database_url() so `alembic upgrade head`
reads the exact same DATABASE_URL every repository function already does
(including in tests, against whichever Postgres TEST_DATABASE_URL/
testcontainers pointed DATABASE_URL at for that run)."""
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from db.connection import get_database_url  # noqa: E402

config = context.config
if config.config_file_name is not None:
    # disable_existing_loggers=True (the default) would silently kill every
    # logger already alive when this runs -- including uvicorn's own access/
    # error loggers, since init_db() (and this migration run) happens at
    # main.py import time, before uvicorn.Server gets a chance to configure
    # (and re-enable) its own loggers.
    fileConfig(config.config_file_name, disable_existing_loggers=False)

config.set_main_option("sqlalchemy.url", get_database_url())

target_metadata = None


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
